#!/usr/bin/env groovy
pipeline {
    agent { label "dockermgr" }
    stages{
        stage('Docker build'){
          steps {
              sh """
                docker-compose build
              """
          }
        }
    }
}